name: shinchan
description: Shinchan and Isolate test

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: "2.10.2"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.4
  rxdart: 0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
